# Caméra 
CAMERA_INDEX = 0  
CAMERA_FPS = 30
CAMERA_AUTOFOCUS = True
CAMERA_WIDTH = 3840
CAMERA_HEIGHT = 2160 

# Écran 
DISPLAY_WIDTH = 1920 
DISPLAY_HEIGHT = 1080

# Preview 
PREVIEW_WIDTH = 960
PREVIEW_HEIGHT = 720

# GPIO 
BUTTON_PIN = 17 
FLASH_PIN = 27  
BUTTON_BOUNCE = 0.05  
FLASH_PULSE_DURATION = 0.05  
FLASH_ON_DELAY = 0.1  

# Comportement 
COUNTDOWN = 3  
REVIEW_DURATION = 3 

# Sauvegarde 
SAVE_DIR = "/home/pi/photos"
PHOTO_FORMAT = "jpg"
JPEG_QUALITY = 100
